CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS companies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES companies(id), email text NOT NULL, role text NOT NULL CHECK (role IN ('admin','analyst','viewer')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(company_id,email));
CREATE TABLE IF NOT EXISTS parcels (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES companies(id), name text NOT NULL, crop text, geometry jsonb NOT NULL, area_ha numeric NOT NULL CHECK(area_ha > 0), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS analysis_jobs (id uuid PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(id), parcel_id uuid REFERENCES parcels(id), mode text NOT NULL CHECK(mode IN ('LIVE','DEMO')), status text NOT NULL, stage integer NOT NULL DEFAULT 0, stages jsonb NOT NULL DEFAULT '[]', error_code text, error_message text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS satellite_scenes (id text PRIMARY KEY, provider text NOT NULL, acquired_at timestamptz NOT NULL, cloud_cover numeric, metadata jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS analyses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES companies(id), parcel_id uuid REFERENCES parcels(id), job_id uuid REFERENCES analysis_jobs(id), scene_id text REFERENCES satellite_scenes(id), algorithm_version text NOT NULL, mode text NOT NULL CHECK(mode IN ('LIVE','DEMO')), geometry jsonb NOT NULL, result jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS observations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), analysis_id uuid NOT NULL REFERENCES analyses(id) ON DELETE CASCADE, scene_id text REFERENCES satellite_scenes(id), acquired_at timestamptz NOT NULL, index_name text NOT NULL, value numeric NOT NULL, unit text NOT NULL, valid_pixel_ratio numeric, cloud_ratio numeric, shadow_ratio numeric, algorithm_version text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), analysis_id uuid NOT NULL REFERENCES analyses(id) ON DELETE CASCADE, type text NOT NULL, source text NOT NULL, source_id text, observed_at timestamptz, value jsonb NOT NULL, unit text, status text NOT NULL CHECK(status IN ('MEASURED','ESTIMATED','AI_INFERENCE','FIELD_VERIFIED')), confidence text, verification_status text NOT NULL, methodology text NOT NULL);
CREATE TABLE IF NOT EXISTS practice_signals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), analysis_id uuid NOT NULL REFERENCES analyses(id) ON DELETE CASCADE, type text NOT NULL, status text NOT NULL, payload jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS weather_observations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES companies(id), parcel_id uuid REFERENCES parcels(id), provider text NOT NULL, observed_at timestamptz NOT NULL, location jsonb NOT NULL, units jsonb NOT NULL, payload jsonb NOT NULL, fetched_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mrv_reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES companies(id), analysis_id uuid NOT NULL REFERENCES analyses(id), version text NOT NULL, sha256 text NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS report_artifacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), report_id uuid NOT NULL REFERENCES mrv_reports(id) ON DELETE CASCADE, kind text NOT NULL, storage_key text NOT NULL, sha256 text NOT NULL, size_bytes bigint NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS field_verifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES companies(id), parcel_id uuid NOT NULL REFERENCES parcels(id), evidence_id uuid REFERENCES evidence(id), status text NOT NULL, payload jsonb NOT NULL, verified_by uuid REFERENCES users(id), verified_at timestamptz);
CREATE TABLE IF NOT EXISTS analysis_cache (cache_key text PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(id), algorithm_version text NOT NULL, payload jsonb NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_logs (id bigserial PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(id), user_id uuid, action text NOT NULL, entity_type text NOT NULL, entity_id text, request_id text, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_parcels_company ON parcels(company_id);
CREATE INDEX IF NOT EXISTS idx_analyses_company_parcel ON analyses(company_id,parcel_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_company_created ON analysis_jobs(company_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reports_company_created ON mrv_reports(company_id,created_at DESC);

